initialization
initializeLabels

	projectActions label: 'Project Actions'.
	newProjectButton label: self translator tNew.
	saveProjectButton label: self translator tSave.
	openFromFileButton label: self translator tOpen.
	editProjectButton label: self translator tProperties.	
	exploreProjectButton label: self translator tExplore.
	removeProjectButton label: self translator tRemove.
	closeProjectButton label: self translator tClose.
	closeWindowButton label: self translator tQuit.
	preferencesButton label: self translator tPreferences.
	recentProjectsLabel label: 'Recent Projects'.
