initialization
initializeLabels

	projectActions label: 'Project Actions'.
	newProjectButton label: 'Create New Project...'.
	saveProjectButton label: 'Save Current Project'.
	openFromFileButton label: 'Open...'.
	editProjectButton label: 'Edit Current Project...'.	
	exploreProjectButton label: 'Explore Current Project...'.
	removeProjectButton label: 'Remove Current Project...'.
	closeProjectButton label: 'Close Current Project'.
	closeWindowButton label: 'Close'.
	recentProjectsLabel label: 'Recent Projects'.
