initialization
initializePrvWidgets
	" Private - See superimplementor's comment "

	projectActions := self newLabel.
	newProjectButton := self newButton.
	openFromFileButton := self newButton.
	exploreProjectButton := self newButton.
	removeProjectButton := self newButton.
	closeProjectButton := self newButton.
	saveProjectButton := self newButton.
	editProjectButton := self newButton. 
	closeWindowButton := self newButton.