baselines
baselineDependencies: spec

	spec
		baseline: 'CommonUtils'
		with: [ spec repository: 'github://hernanmd/CommonUtils:v1.0.3/repository' ].
	spec
		baseline: 'SpecUIAddOns'
		with: [ spec repository: 'github://hernanmd/SpecUIAddOns/repository' ].
	spec
		baseline: 'OrderedSet'
		with: [ spec repository: 'github://hernanmd/OrderedSet:v1.0.0/repository' ].
	spec
		baseline: 'FileDialog'
		with: [ spec repository: 'github://peteruhnak/file-dialog:v1.x/repository' ].
	spec
		baseline: 'I18N'
		with: [ spec repository: 'github://astares/Pharo-I18N:v1.0.0/src' ].
	spec
		baseline: 'SState'
		with: [ spec repository: 'github://mumez/SState:v1.0.0/repository' ].